### ISSUE TITLE
Show transformations in output

### ISSUE THREAD

**Issue by lancioni** [soras/genEditDist#1]
Thank you for the wonderful program! Is there a way to show which transformations are used to produce the best matches? It is showed in the readme, but no flags seem to be available to show that in the output, too.

**Comment by soras** [comment]
Thank you for the interest! 
Unfortunately, the current version of the program does not have the option of showing transformations. 
From earlier times, we do have some code for showing the transformations, but that comes as a separate program, and it's not fully compatible with the current version (e.g. it does not account for the "blocked regions") -- it needs some work on the integration. Otherwise, I agree that this functionality would be neat, and I'll try to add it in future (I can't promise it anytime soon, though).

**Comment by lancioni** [comment]
Thank you for your answer!

In fact, I managed to compile the project in Windows under Cygwin (I have also a Linux distribution in dual-boot on the pc, but I’ll need it under Windows), and I’ll try to modify the source, if I can. Unfortunately, I’m much more fluent in Python and in Java than in C, but your source code is wonderfully commented.

Best wishes,

Giuliano

# 

Prof. Giuliano Lancioni
Lingua e Letteratura Araba
Dipartimento di Lingue, Letterature e Culture Straniere
Università Roma Tre
via Ostiense, 236
00146 Roma
Tel: + 39 06 5733.8345
Fax: + 39 06 5733.8344
mailto:giuliano.lancioni@uniroma3.it
http://host.uniroma3.it/docenti/lancioni

Da: Siim Orasmaa [mailto:notifications@github.com]
Inviato: domenica 24 gennaio 2016 16:12
A: soras/genEditDist genEditDist@noreply.github.com
Cc: Giuliano Lancioni giuliano.lancioni@uniroma3.it
Oggetto: Re: [genEditDist] Show transformations in output (#1)

Thank you for the interest!
Unfortunately, the current version of the program does not have the option of showing transformations.
From earlier times, we do have some code for showing the transformations, but that comes as a separate program, and it's not fully compatible with the current version (e.g. it does not account for the "blocked regions") -- it needs some work on the integration. Otherwise, I agree that this functionality would be neat, and I'll try to add it in future (I can't promise it anytime soon, though).

**Comment by soras** [comment]
I added the functionality of showing the transformations / alignments into the tool. 
Though it currently has some limitations (e.g. it can only be used with the flag -m and in the full extent search mode), hopefully it still provides to be useful.
